
-- Schéma

DROP SCHEMA IF EXISTS quizzbus CASCADE;
CREATE SCHEMA quizzbus;


-- Tables

CREATE TABLE compte (
	idcompte		INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(25)		NOT NULL,
	motdepasse		VARCHAR(25) 	NOT NULL,
	email			VARCHAR(100)	NOT NULL,
	flagadmin		BOOLEAN			NOT NULL	DEFAULT FALSE,
	UNIQUE (pseudo),
	PRIMARY KEY (idcompte)
);
